name: batch5pm
description: A new Flutter project.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: '>=2.19.6 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  cached_network_image: ^3.1.0
  intl_phone_field: ^3.2.0
  intl: ^0.17.0
  image_picker: ^1.0.0
  shared_preferences: ^2.3.0
  http: ^1.2.2
  dio: ^5.5.0
  location: ^5.0.0
  app_settings: ^5.1.1
  infinite_scroll_pagination: ^4.0.0
  carousel_slider: ^5.0.0
  device_info_plus: ^10.1.2
#  locked_shared_preferences:
#    path: "./packages/locked_shared_preferences"

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - images/